#!/bin/sh
printf "Enter phase to compile: Ex. 1, 2, 3, 4\n"
read PHASENUM

javac phase_$PHASENUM/*.java

if [ "$?" != "0" ]; then
    echo "[Error] Compiled with errors" 1>&2
    exit 1
fi
# AppleScript to clear output 
# Several cases online experienced issues
# /usr/bin/osascript -e 'tell application "System Events" to tell process "Terminal" to keystroke "k" using command down'

clear && printf '\e[3J' # Faster than AppleScript and better for scripts

printf "Succesfully compiled.\n\n"

java phase_$PHASENUM.Phase$PHASENUM
# java phase_.TSP_GA

