#!/bin/sh
printf "Enter phase to compile: Ex. 1, 2, 3, 4\n"
read PHASENUM

javac phase_$PHASENUM/*.java

if [ "$?" != "0" ]; then
    echo "[Error] Compiled with errors -> check if folder exists." 1>&2
    exit 1
fi
/usr/bin/osascript -e 'tell application "System Events" to tell process "Terminal" to keystroke "k" using command down'

printf "Succesfully compiled.\n"

java phase_$PHASENUM.Phase$PHASENUM

